title: Chendi Xue's blog
description: Chendi Xue's blog about spark, kubernetes, ceph, c/c++ and etc.
author: Chendi Xue
github: https://github.com/xuechendi
about: I am linux software engineer, currently fosuing on spark, kubernetes, ceph, c/c++, and etc.
disqus_shortname: xuechendi
google_analytics: UA-69358033
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []
permalink: /:year/:month/:day/:title

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/chendixue"
    - icon: fa-github
      link: "https://github.com/xuechendi"
    - icon: fa-instagram
      link: "https://www.instagram.com/xuechendi/"

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Category
      url: /category
    - text: Subscribe
      url: /subscribe

url: "https://xuechendi.github.io"
baseurl: ""
posts_img_path: "/static/img"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
